services:
  starplayer:
    image: ghcr.io/nullredvector/starplayer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /mnt/zion/enc/archive/Downloads/incomplete/content2/shorts:/archive
    environment:
      - ARCHIVE_DIR=/archive

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false
